configs {
  key: "xpytest.unit"
  value {
    requirement {
      cpu: 2
      memory: 6
    }
    command: "bash .pfnci/script.sh"
  }
}

configs {
  key: "xpytest.unit.win"
  value {
    requirement {
      cpu: 2
      memory: 6
      image: "windows"
    }
    time_limit {
      seconds: 1800
    }
    command: ".pfnci\\script.bat"
  }
}
