// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xpytest/proto/test_case.proto

package xpytest_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestResult_Status int32

const (
	TestResult_UNKNOWN  TestResult_Status = 0
	TestResult_SUCCESS  TestResult_Status = 1
	TestResult_INTERNAL TestResult_Status = 2
	TestResult_FAILED   TestResult_Status = 3
	TestResult_TIMEOUT  TestResult_Status = 4
	TestResult_FLAKY    TestResult_Status = 5
)

var TestResult_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "INTERNAL",
	3: "FAILED",
	4: "TIMEOUT",
	5: "FLAKY",
}
var TestResult_Status_value = map[string]int32{
	"UNKNOWN":  0,
	"SUCCESS":  1,
	"INTERNAL": 2,
	"FAILED":   3,
	"TIMEOUT":  4,
	"FLAKY":    5,
}

func (x TestResult_Status) String() string {
	return proto.EnumName(TestResult_Status_name, int32(x))
}
func (TestResult_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_test_case_84f24dfca25eb702, []int{1, 0}
}

type TestQuery struct {
	// File path to a python test.
	File string `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	// Priority.  A test with a higher priority should precede.  This should be
	// useful to avoid slow tests from wasting time because of starting late.
	Priority int32 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	// Deadline in seconds.
	Deadline float32 `protobuf:"fixed32,3,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// # of processes in pytest-xdist.
	Xdist int32 `protobuf:"varint,4,opt,name=xdist,proto3" json:"xdist,omitempty"`
	// # of retries.
	Retry int32 `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	// Resource usage multiplier.
	Resource             float32  `protobuf:"fixed32,6,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestQuery) Reset()         { *m = TestQuery{} }
func (m *TestQuery) String() string { return proto.CompactTextString(m) }
func (*TestQuery) ProtoMessage()    {}
func (*TestQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_case_84f24dfca25eb702, []int{0}
}
func (m *TestQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestQuery.Unmarshal(m, b)
}
func (m *TestQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestQuery.Marshal(b, m, deterministic)
}
func (dst *TestQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestQuery.Merge(dst, src)
}
func (m *TestQuery) XXX_Size() int {
	return xxx_messageInfo_TestQuery.Size(m)
}
func (m *TestQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_TestQuery.DiscardUnknown(m)
}

var xxx_messageInfo_TestQuery proto.InternalMessageInfo

func (m *TestQuery) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *TestQuery) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *TestQuery) GetDeadline() float32 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *TestQuery) GetXdist() int32 {
	if m != nil {
		return m.Xdist
	}
	return 0
}

func (m *TestQuery) GetRetry() int32 {
	if m != nil {
		return m.Retry
	}
	return 0
}

func (m *TestQuery) GetResource() float32 {
	if m != nil {
		return m.Resource
	}
	return 0
}

type TestResult struct {
	Status TestResult_Status `protobuf:"varint,1,opt,name=status,proto3,enum=xpytest.proto.TestResult_Status" json:"status,omitempty"`
	// Test name (e.g., "tests/foo_tests/test_bar.py").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Standard output.
	Stdout string `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Standard error.
	Stderr string `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Duration that the test took.
	Time                 float32  `protobuf:"fixed32,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResult) Reset()         { *m = TestResult{} }
func (m *TestResult) String() string { return proto.CompactTextString(m) }
func (*TestResult) ProtoMessage()    {}
func (*TestResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_case_84f24dfca25eb702, []int{1}
}
func (m *TestResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResult.Unmarshal(m, b)
}
func (m *TestResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResult.Marshal(b, m, deterministic)
}
func (dst *TestResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResult.Merge(dst, src)
}
func (m *TestResult) XXX_Size() int {
	return xxx_messageInfo_TestResult.Size(m)
}
func (m *TestResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResult.DiscardUnknown(m)
}

var xxx_messageInfo_TestResult proto.InternalMessageInfo

func (m *TestResult) GetStatus() TestResult_Status {
	if m != nil {
		return m.Status
	}
	return TestResult_UNKNOWN
}

func (m *TestResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestResult) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *TestResult) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func (m *TestResult) GetTime() float32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type HintFile struct {
	// TODO(imos): Deprecate this once it is confirmed that no one uses this.
	SlowTests            []*HintFile_Rule `protobuf:"bytes,1,rep,name=slow_tests,json=slowTests,proto3" json:"slow_tests,omitempty"`
	Rules                []*HintFile_Rule `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HintFile) Reset()         { *m = HintFile{} }
func (m *HintFile) String() string { return proto.CompactTextString(m) }
func (*HintFile) ProtoMessage()    {}
func (*HintFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_case_84f24dfca25eb702, []int{2}
}
func (m *HintFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HintFile.Unmarshal(m, b)
}
func (m *HintFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HintFile.Marshal(b, m, deterministic)
}
func (dst *HintFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HintFile.Merge(dst, src)
}
func (m *HintFile) XXX_Size() int {
	return xxx_messageInfo_HintFile.Size(m)
}
func (m *HintFile) XXX_DiscardUnknown() {
	xxx_messageInfo_HintFile.DiscardUnknown(m)
}

var xxx_messageInfo_HintFile proto.InternalMessageInfo

func (m *HintFile) GetSlowTests() []*HintFile_Rule {
	if m != nil {
		return m.SlowTests
	}
	return nil
}

func (m *HintFile) GetRules() []*HintFile_Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

type HintFile_Rule struct {
	// File name of a slow test (e.g.,"test_foo.py", "bar/test_foo.py").  Parent
	// directories can be omitted (i.e., "test_foo.py" can matches
	// "bar/test_foo.py").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Deadline in seconds.
	Deadline float32 `protobuf:"fixed32,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	// # of processes in pytest-xdist.
	Xdist int32 `protobuf:"varint,3,opt,name=xdist,proto3" json:"xdist,omitempty"`
	// # of retries.  For flaky tests.
	Retry int32 `protobuf:"varint,4,opt,name=retry,proto3" json:"retry,omitempty"`
	// Resource usage multiplier (default: 1.0).
	Resource             float32  `protobuf:"fixed32,5,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HintFile_Rule) Reset()         { *m = HintFile_Rule{} }
func (m *HintFile_Rule) String() string { return proto.CompactTextString(m) }
func (*HintFile_Rule) ProtoMessage()    {}
func (*HintFile_Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_case_84f24dfca25eb702, []int{2, 0}
}
func (m *HintFile_Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HintFile_Rule.Unmarshal(m, b)
}
func (m *HintFile_Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HintFile_Rule.Marshal(b, m, deterministic)
}
func (dst *HintFile_Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HintFile_Rule.Merge(dst, src)
}
func (m *HintFile_Rule) XXX_Size() int {
	return xxx_messageInfo_HintFile_Rule.Size(m)
}
func (m *HintFile_Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_HintFile_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_HintFile_Rule proto.InternalMessageInfo

func (m *HintFile_Rule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HintFile_Rule) GetDeadline() float32 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func (m *HintFile_Rule) GetXdist() int32 {
	if m != nil {
		return m.Xdist
	}
	return 0
}

func (m *HintFile_Rule) GetRetry() int32 {
	if m != nil {
		return m.Retry
	}
	return 0
}

func (m *HintFile_Rule) GetResource() float32 {
	if m != nil {
		return m.Resource
	}
	return 0
}

func init() {
	proto.RegisterType((*TestQuery)(nil), "xpytest.proto.TestQuery")
	proto.RegisterType((*TestResult)(nil), "xpytest.proto.TestResult")
	proto.RegisterType((*HintFile)(nil), "xpytest.proto.HintFile")
	proto.RegisterType((*HintFile_Rule)(nil), "xpytest.proto.HintFile.Rule")
	proto.RegisterEnum("xpytest.proto.TestResult_Status", TestResult_Status_name, TestResult_Status_value)
}

func init() {
	proto.RegisterFile("xpytest/proto/test_case.proto", fileDescriptor_test_case_84f24dfca25eb702)
}

var fileDescriptor_test_case_84f24dfca25eb702 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4d, 0x8b, 0xd4, 0x40,
	0x10, 0xb5, 0xf3, 0xe5, 0xa4, 0x56, 0x25, 0x34, 0x22, 0x61, 0x51, 0x08, 0x39, 0xe5, 0x94, 0x85,
	0xf1, 0x22, 0x78, 0x1a, 0xd6, 0x0c, 0x0e, 0x3b, 0x66, 0xb1, 0x93, 0x41, 0x3c, 0x2d, 0x71, 0x53,
	0x42, 0x20, 0x3b, 0x19, 0xba, 0x3b, 0xb8, 0xb9, 0xf8, 0x57, 0xfc, 0x93, 0xde, 0xbc, 0x48, 0x75,
	0xb2, 0xe3, 0x8c, 0x38, 0xe0, 0xad, 0x5e, 0xf5, 0xab, 0xea, 0xf7, 0xea, 0xc1, 0xab, 0xfb, 0xdd,
	0xa0, 0x51, 0xe9, 0x8b, 0x9d, 0xec, 0x74, 0x77, 0x41, 0xe5, 0xcd, 0x6d, 0xa5, 0x30, 0x35, 0x98,
	0x3f, 0x9d, 0x9e, 0x47, 0x18, 0xff, 0x60, 0xe0, 0x97, 0xa8, 0xf4, 0xc7, 0x1e, 0xe5, 0xc0, 0x39,
	0x38, 0x5f, 0x9b, 0x16, 0x43, 0x16, 0xb1, 0xc4, 0x17, 0xa6, 0xe6, 0xe7, 0x30, 0xdb, 0xc9, 0xa6,
	0x93, 0x8d, 0x1e, 0x42, 0x2b, 0x62, 0x89, 0x2b, 0xf6, 0x98, 0xde, 0x6a, 0xac, 0xea, 0xb6, 0xd9,
	0x62, 0x68, 0x47, 0x2c, 0xb1, 0xc4, 0x1e, 0xf3, 0xe7, 0xe0, 0xde, 0xd7, 0x8d, 0xd2, 0xa1, 0x63,
	0x86, 0x46, 0x40, 0x5d, 0x89, 0x5a, 0x0e, 0xa1, 0x3b, 0x76, 0x0d, 0xa0, 0x3d, 0x12, 0x55, 0xd7,
	0xcb, 0x5b, 0x0c, 0xbd, 0x71, 0xcf, 0x03, 0x8e, 0x7f, 0x32, 0x00, 0x52, 0x28, 0x50, 0xf5, 0xad,
	0xe6, 0x6f, 0xc0, 0x53, 0xba, 0xd2, 0xbd, 0x32, 0x22, 0x9f, 0xcd, 0xa3, 0xf4, 0xc8, 0x50, 0xfa,
	0x87, 0x9a, 0x16, 0x86, 0x27, 0x26, 0x3e, 0x99, 0xdb, 0x56, 0x77, 0x68, 0x4c, 0xf8, 0xc2, 0xd4,
	0xfc, 0x05, 0x6d, 0xab, 0xbb, 0x5e, 0x1b, 0xf9, 0xbe, 0x98, 0xd0, 0xd4, 0x47, 0x29, 0x8d, 0xfa,
	0xb1, 0x8f, 0x52, 0xd2, 0x0e, 0xdd, 0xdc, 0xa1, 0x51, 0x6f, 0x09, 0x53, 0xc7, 0x25, 0x78, 0xe3,
	0x4f, 0xfc, 0x0c, 0x1e, 0x6f, 0xf2, 0xab, 0xfc, 0xfa, 0x53, 0x1e, 0x3c, 0x22, 0x50, 0x6c, 0x2e,
	0x2f, 0xb3, 0xa2, 0x08, 0x18, 0x7f, 0x02, 0xb3, 0x55, 0x5e, 0x66, 0x22, 0x5f, 0xac, 0x03, 0x8b,
	0x03, 0x78, 0xcb, 0xc5, 0x6a, 0x9d, 0xbd, 0x0b, 0x6c, 0xa2, 0x95, 0xab, 0x0f, 0xd9, 0xf5, 0xa6,
	0x0c, 0x1c, 0xee, 0x83, 0xbb, 0x5c, 0x2f, 0xae, 0x3e, 0x07, 0x6e, 0xfc, 0x8b, 0xc1, 0xec, 0x7d,
	0xb3, 0xd5, 0x4b, 0xca, 0xe0, 0x2d, 0x80, 0x6a, 0xbb, 0x6f, 0x37, 0xe4, 0x93, 0x8c, 0xdb, 0xc9,
	0xd9, 0xfc, 0xe5, 0x5f, 0xc6, 0x1f, 0xc8, 0xa9, 0xe8, 0x5b, 0x14, 0x3e, 0xf1, 0xe9, 0x16, 0x8a,
	0xcf, 0xc1, 0x95, 0x7d, 0x8b, 0x2a, 0xb4, 0xfe, 0x63, 0x6e, 0xa4, 0x9e, 0x7f, 0x07, 0x87, 0xe0,
	0xfe, 0x66, 0xec, 0xe0, 0x66, 0x87, 0xa1, 0x5b, 0xa7, 0x42, 0xb7, 0xff, 0x19, 0xba, 0x73, 0x2a,
	0x74, 0xf7, 0x38, 0xf4, 0x2f, 0x9e, 0xd1, 0xf6, 0xfa, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e,
	0x55, 0x16, 0xfe, 0xcd, 0x02, 0x00, 0x00,
}
